# SENTIMENT ANALYSIS OF ASDA REVIEWS ON TRUSTPILOT - DATA COLLECTION

The goal of this notebook is to perform data collection of ASDA review on Trustpilot. 

### Importing Libraries

In [135]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import json
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import re
from textblob import TextBlob
from wordcloud import WordCloud
import seaborn as sns
import matplotlib.pyplot as plt
import cufflinks as cf
from plotly.offline import init_notebook_mode, iplot 
init_notebook_mode(connected =True)
cf.go_offline();
import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")
pd.set_option("display.max_columns", None)

## DATA COLLECTION

Data was collected by web scraping ASDA review page on Trustpilot using beautiful soup. The HTML was inspected and and various elements holding the data i wanted was idetified. This was then saved to a csv file and also dataframed. VPN was also used for changing IP address so when IP got to limit another was used.

## Scraping the HTML from TrustPilot for ASDA reviews

In [136]:
from bs4 import BeautifulSoup, SoupStrainer


In [137]:


# Initialize empty lists to store review data
allUsers = []
allRatings = []
allLocations = []
allDates = []
allExpDate = []
allReviewHeading = []
allReviewContent = []

# Set the maximum number of pages to scrape. maximum number of pages as at day data was scraped
max_pages = 674

# Loop through each page
for current_page in range(1, max_pages + 1):
    url = f"https://uk.trustpilot.com/review/www.asda.com?page={current_page}"
    result = requests.get(url)

    # Check if the request was successful
    if result.status_code != 200:
        print(f"Failed to retrieve page {current_page}. Status Code: {result.status_code}")
        break

    soup = BeautifulSoup(result.content, "html.parser")
    reviews = soup.find_all("div", class_="styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ")

    # Check if there are reviews on the page
    if not reviews:
        print(f"No reviews found on page {current_page}. Stopping...")
        break

#After inspecting the page i found the elements holding the different dat i wanted
        
    for review in reviews:
        # Extract user name
        user = review.find("span", class_="typography_heading-xxs__QKBS8 typography_appearance-default__AAY17").text
        allUsers.append(user)

        # Extract star rating
        star_rating_div = review.find("img")
        # Find the 'img' tag
        img_tag = review.find('img')
        # Extract the 'alt' attribute, which contains the star rating
        alt_text = img_tag.get('alt', '')
        # Extracting the star rating as a number
        star_rating = int(alt_text.split()[1]) if 'Rated' in alt_text else None
        allRatings.append(star_rating)

        # Extract location (if available)
        location_elem = review.find("div", class_="typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l styles_detailsIcon__Fo_ua")
        location = location_elem.span.string if location_elem else ""
        allLocations.append(location)

        # Extract review date
        time_tag = review.find('time')
        date_string = time_tag['datetime']
        date = datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S.%fZ")
        allDates.append(date)

        # Extract experience date
        p_tags = review.find_all('p')
        for p_tag in p_tags:
            if "Date of experience" in p_tag.text:
                date_string = p_tag.get_text(strip=True).split(':')[1].strip()
                try:
                    expDate = datetime.strptime(date_string, "%d %B %Y")
                    allExpDate.append(expDate)
                except ValueError as e:
                    print(f"Error parsing experience date on page {current_page}: {e}")
                break  # Stop searching for the experience date once found

        # Extract review heading
        review_heading_tag = review.find('h2', {"data-service-review-title-typography": "true"})
        review_heading = review_heading_tag.text.strip()
        allReviewHeading.append(review_heading)

        # Extract review content (if available)
        review_paragraph = review.find('p', {"data-service-review-text-typography": "true"})
        review_content = review_paragraph.text.strip() if review_paragraph else ""
        allReviewContent.append(review_content)

# Create a DataFrame from the extracted data
df = pd.DataFrame({
    "User": allUsers,
    "Rating": allRatings,
    "Location": allLocations,
    "Date": allDates,
    "ExperienceDate": allExpDate,
    "ReviewHeading": allReviewHeading,
    "ReviewContent": allReviewContent
})



Failed to retrieve page 287. Status Code: 403


IP addresss failed to retrive beyong page 287 so i repeat code this time starting from page 305

In [139]:
# Initialize empty lists to store review data
allUsers = []
allRatings = []
allLocations = []
allDates = []
allExpDate = []
allReviewHeading = []
allReviewContent = []


# Set the maximum number of pages to scrape
max_pages = 674

# Loop through each page
for current_page in range(287, max_pages + 1):
    url = f"https://uk.trustpilot.com/review/www.asda.com?page={current_page}"
    result = requests.get(url)

    # Check if the request was successful
    if result.status_code != 200:
        print(f"Failed to retrieve page {current_page}. Status Code: {result.status_code}")
        break

    soup = BeautifulSoup(result.content, "html.parser")
    reviews = soup.find_all("div", class_="styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ")

    # Check if there are reviews on the page
    if not reviews:
        print(f"No reviews found on page {current_page}. Stopping...")
        break

#After inspecting the page i found the elements holding the different dat i wanted
        
    for review in reviews:
        # Extract user name
        user = review.find("span", class_="typography_heading-xxs__QKBS8 typography_appearance-default__AAY17").text
        allUsers.append(user)

        # Extract star rating
        star_rating_div = review.find("img")
        # Find the 'img' tag
        img_tag = review.find('img')
        # Extract the 'alt' attribute, which contains the star rating
        alt_text = img_tag.get('alt', '')
        # Extracting the star rating as a number
        star_rating = int(alt_text.split()[1]) if 'Rated' in alt_text else None
        allRatings.append(star_rating)

        # Extract location (if available)
        location_elem = review.find("div", class_="typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l styles_detailsIcon__Fo_ua")
        location = location_elem.span.string if location_elem else ""
        allLocations.append(location)

        # Extract review date
        time_tag = review.find('time')
        date_string = time_tag['datetime']
        date = datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S.%fZ")
        allDates.append(date)

        # Extract experience date
        p_tags = review.find_all('p')
        for p_tag in p_tags:
            if "Date of experience" in p_tag.text:
                date_string = p_tag.get_text(strip=True).split(':')[1].strip()
                try:
                    expDate = datetime.strptime(date_string, "%d %B %Y")
                    allExpDate.append(expDate)
                except ValueError as e:
                    print(f"Error parsing experience date on page {current_page}: {e}")
                break  # Stop searching for the experience date once found

        # Extract review heading
        review_heading_tag = review.find('h2', {"data-service-review-title-typography": "true"})
        review_heading = review_heading_tag.text.strip()
        allReviewHeading.append(review_heading)

        # Extract review content (if available)
        review_paragraph = review.find('p', {"data-service-review-text-typography": "true"})
        review_content = review_paragraph.text.strip() if review_paragraph else ""
        allReviewContent.append(review_content)

# Create a DataFrame from the extracted data
df1 = pd.DataFrame({
    "User": allUsers,
    "Rating": allRatings,
    "Location": allLocations,
    "Date": allDates,
    "ExperienceDate": allExpDate,
    "ReviewHeading": allReviewHeading,
    "ReviewContent": allReviewContent
})



Failed to retrieve page 530. Status Code: 403


repeat the above starting from page 530 and saving in dataframe df2

In [141]:
# Initialize empty lists to store review data
allUsers = []
allRatings = []
allLocations = []
allDates = []
allExpDate = []
allReviewHeading = []
allReviewContent = []


# Set the maximum number of pages to scrape
max_pages = 674

# Loop through each page
for current_page in range(530, max_pages + 1):
    url = f"https://uk.trustpilot.com/review/www.asda.com?page={current_page}"
    result = requests.get(url)

    # Check if the request was successful
    if result.status_code != 200:
        print(f"Failed to retrieve page {current_page}. Status Code: {result.status_code}")
        break

    soup = BeautifulSoup(result.content, "html.parser")
    reviews = soup.find_all("div", class_="styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ")

    # Check if there are reviews on the page
    if not reviews:
        print(f"No reviews found on page {current_page}. Stopping...")
        break

#After inspecting the page i found the elements holding the different dat i wanted
        
    for review in reviews:
        # Extract user name
        user = review.find("span", class_="typography_heading-xxs__QKBS8 typography_appearance-default__AAY17").text
        allUsers.append(user)

        # Extract star rating
        star_rating_div = review.find("img")
        # Find the 'img' tag
        img_tag = review.find('img')
        # Extract the 'alt' attribute, which contains the star rating
        alt_text = img_tag.get('alt', '')
        # Extracting the star rating as a number
        star_rating = int(alt_text.split()[1]) if 'Rated' in alt_text else None
        allRatings.append(star_rating)

        # Extract location (if available)
        location_elem = review.find("div", class_="typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l styles_detailsIcon__Fo_ua")
        location = location_elem.span.string if location_elem else ""
        allLocations.append(location)

        # Extract review date
        time_tag = review.find('time')
        date_string = time_tag['datetime']
        date = datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S.%fZ")
        allDates.append(date)

        # Extract experience date
        p_tags = review.find_all('p')
        for p_tag in p_tags:
            if "Date of experience" in p_tag.text:
                date_string = p_tag.get_text(strip=True).split(':')[1].strip()
                try:
                    expDate = datetime.strptime(date_string, "%d %B %Y")
                    allExpDate.append(expDate)
                except ValueError as e:
                    print(f"Error parsing experience date on page {current_page}: {e}")
                break  # Stop searching for the experience date once found

        # Extract review heading
        review_heading_tag = review.find('h2', {"data-service-review-title-typography": "true"})
        review_heading = review_heading_tag.text.strip()
        allReviewHeading.append(review_heading)

        # Extract review content (if available)
        review_paragraph = review.find('p', {"data-service-review-text-typography": "true"})
        review_content = review_paragraph.text.strip() if review_paragraph else ""
        allReviewContent.append(review_content)

# Create a DataFrame from the extracted data
df2 = pd.DataFrame({
    "User": allUsers,
    "Rating": allRatings,
    "Location": allLocations,
    "Date": allDates,
    "ExperienceDate": allExpDate,
    "ReviewHeading": allReviewHeading,
    "ReviewContent": allReviewContent
})



No more errors. Now we have three dataframes which i will concatenate

In [145]:
# Concatenating the DataFrames vertically
joined = pd.concat([df, df1, df2], ignore_index=True)
df = joined

User  Rating Location                Date ExperienceDate   
13465          Joyce     3.0       IN 2009-07-09 17:06:50     2009-07-09  \
13466        d young     1.0       GB 2009-06-09 08:57:17     2009-06-09   
13467            B L     1.0       GB 2009-05-20 16:29:05     2009-05-20   
13468  Zena Gledhill     1.0       IR 2009-03-07 16:25:25     2009-03-07   
13469          Cilla     2.0       GB 2009-01-15 13:41:54     2009-01-15   

                                 ReviewHeading   
13465                            Slow delivery  \
13466  problems with them in the past 6 months   
13467                Two orders, Zero received   
13468                           Ethical or not   
13469                       Non delivery of CD   

                                           ReviewContent  
13465  Had to wait a week for my new garden set, slow...  
13466  i am doing an assignment at college as part of...  
13467  Ordered a game a while ago which would be disp...  
13468  Do you think it is ethical of asda to use a tr...  
13469  Ordered a cd on the 17th Dec 2008 still had no...

In [148]:
# Convert the "Date" column to datetime
df["Date"] = pd.to_datetime(df["Date"])
df["ExperienceDate"] = pd.to_datetime(df["ExperienceDate"])

# Save the filtered DataFrame to a CSV file
df.to_csv("trustpilot_reviews.csv", index=False)

In [149]:
# Filter reviews from 2017 to September 2023
start_date = datetime(2017, 1, 1)
end_date = datetime(2023, 9, 30)
filtered_df = df[(df["ExperienceDate"] >= start_date) & (df["ExperienceDate"] <= end_date)]

# Save the filtered DataFrame to a CSV file
filtered_df.to_csv("filtered_trustpilot_reviews.csv", index=False)



In [150]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10790 entries, 16 to 11009
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   User            10790 non-null  object        
 1   Rating          8546 non-null   float64       
 2   Location        10790 non-null  object        
 3   Date            10790 non-null  datetime64[ns]
 4   ExperienceDate  10790 non-null  datetime64[ns]
 5   ReviewHeading   10790 non-null  object        
 6   ReviewContent   10790 non-null  object        
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 674.4+ KB


Confirming the end date for the period of analysis

In [151]:
# Getting the later dates
filtered_df.head()

User  Rating Location                Date ExperienceDate   
16   Nichola     1.0       GB 2023-10-24 05:22:49     2023-09-15  \
21  Robert B     1.0       GB 2023-10-22 10:45:01     2023-09-01   
22       Tom     1.0       GB 2023-10-25 10:29:52     2023-09-27   
47       Uno     NaN       GB 2023-10-22 07:18:18     2023-07-15   
99      Iain     1.0       GB 2023-10-11 01:03:43     2023-06-12   

                                  ReviewHeading   
16   I went in the large Asda Worksop S80 todo…  \
21                          Never work for asda   
22  ASDA - not refunding and not communicating.   
47                                      RUBBISH   
99        Asda Irvine rude staff member behind…   

                                        ReviewContent  
16  I went in the Asda Worksop S80 3NE todo my wee...  
21  Don't ever work for asda ....Wanted to work fo...  
22  Ordered online £72.00 of items.ASDA amended th...  
47  RUBBISH , I had so many orders and every time ...  
99  Asda Irvine rude staff member behind counter t...

In [152]:
# Getting the earlier dates
filtered_df.tail()

User  Rating Location                    Date ExperienceDate   
11005  Julie Driver     NaN       GB 2017-01-05 18:59:56.000     2017-01-05  \
11006      Mo Plumb     NaN       GB 2017-01-04 14:39:44.000     2017-01-04   
11007          Matt     1.0       GB 2017-01-03 16:07:17.837     2017-01-03   
11008   Jim Mccrory     NaN       GB 2017-01-03 14:23:14.000     2017-01-03   
11009           Kat     2.0       GB 2017-01-02 14:35:23.029     2017-01-02   

                                 ReviewHeading   
11005                           waste of money  \
11006  Disappointingly poor service from Asda.   
11007  Home delivery late. Out of date food!!!   
11008                                shocking.   
11009                              Overcharged   

                                           ReviewContent  
11005  I am very upset about my recent asda order. Th...  
11006  Today I received delivery of my Asda shopping ...  
11007  To be honest I don't think Asda care! Don't do...  
11008  I am currently in asda robroyston and can't be...  
11009  I ordered some shirts and a jumper to be deliv...